import Head from "next/head";
import Card from "../src/Card/Card";
import classes from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.card}>
        <Card />
      </div>
      {/* <Quiz /> */}
    </div>
  );
}
